### ISSUE TITLE
Prev/next button active when it shouldn't?

### ISSUE THREAD

**Issue by alexanderzeillinger** [flaviusmatis/simplePagination.js#103]
When I'm on the first or last page the prev/next button is also marked as active and current, is that intended?

![image](https://cloud.githubusercontent.com/assets/126621/7214611/31c28a10-e5b4-11e4-83df-b1f8fce4c016.png)

![image](https://cloud.githubusercontent.com/assets/126621/7214612/3a929112-e5b4-11e4-9096-3336de777f68.png)

**Comment by aguegu** [comment]
I want to issue exactly the same issue. prev/next should be disabled, not active.

**Comment by bilalakil** [comment]
I suppose this was an implementation shortcut.

It seems like the designs that roll out with this plugin treat the situation as follows:

> When on the first page, the previous arrow is applied the same style since you're "already there" (at the start) so to speak, just as you're already on the first page. The last page is similar.

And so, the same class was used for simplicity. As such, I don't believe the resulting appearance is a bug.

However it would technically be better to use a different class (i.e. disabled instead of active) for when other developers wish to customise the CSS, as they may not want to have it designed this way.

**Comment by aguegu** [comment]
![screen shot 2015-06-15 at 12 09 50](https://cloud.githubusercontent.com/assets/1559791/8152978/a207f8b6-1357-11e5-9610-6e1d32998e67.png)

Does it look weird?

**Comment by bilalakil** [comment]
I think having a pagination module with only 1 page would be weird regardless of the design.

I don't think the plugin should worry so much about design specifics. You can use the events it provides to easily control the display as you desire - you may even want to hide the whole thing if there's only one page.

There's no "right way" to do these things - there are a million ways. We just need to make sure that the users of the plugin have the means to easily do whatever it is they may want, and I think that's already there in this case.

Do you have any suggestions though?

**Comment by aguegu** [comment]
I have made a one line pull request for this. Wish it could be a happy ending for this. :)
